# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82c8b9a508e88f786b964781fa53fba8c042087f655ad4029d6ae8680669da941045991273d787d1fdc953a542c8738638fb59f8e6c0bcf26419b2dc45c9528e

test:
  secret_key_base: 11205f89fbbc06089cad52cfb810e85b00d993a4326d48242b6683f1ae4087045d5b9d4eafe8448a36c067255d397e640529e935506bbb5ee2b7b588383c5238

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
